apiVersion: apps/v1
kind: Deployment
metadata:
  name: version-app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: version-app
      version: "2.0.0"
  template:
    metadata:
      labels:
        app: version-app
        version: "2.0.0"
    spec:
      containers:
      - name: version-app
        image: yurabeloded/version-app:v2.0.0
        env:
        - name: VERSION
          value: "2.0.0"
        ports:
        - containerPort: 8080
